# Generated by Django 3.2.4 on 2021-06-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=200, verbose_name='Emaili')),
                ('message', models.CharField(max_length=200, verbose_name='Xabari')),
            ],
            options={
                'verbose_name': 'buyurtma',
                'verbose_name_plural': 'buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=100, verbose_name='Emaili')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('subject', models.CharField(max_length=80, verbose_name='Kasalligi')),
                ('message', models.CharField(max_length=200, verbose_name='Xabari')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contactlar',
            },
        ),
    ]
