# Generated by Django 3.2.4 on 2021-06-28 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='poster/')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='day',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 14, 10, 19, 332149, tzinfo=utc), max_length=80, verbose_name='Day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='doctor',
            field=models.CharField(default=datetime.datetime(2021, 6, 28, 14, 11, 41, 406413, tzinfo=utc), max_length=50, verbose_name='Doktor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 28, 14, 12, 46, 72133, tzinfo=utc), max_length=70, verbose_name='Time'),
            preserve_default=False,
        ),
    ]
