# Generated by Django 3.2.4 on 2021-06-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0002_auto_20210628_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='doctor',
            new_name='medic',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='time',
            new_name='vaqt',
        ),
    ]
